source "https://rubygems.org"

gem "rails", "~> 7.1", ">= 7.1.3"
gem "dotenv"
gem "oj", ">= 2.8.3"
gem "oj_mimic_json", "~> 1.0", ">= 1.0.1"
gem "equivalent-xml", "~> 0.6.0"
gem "nokogiri", ">= 1.11.2"
gem "iso8601", "~> 0.9.0"
gem "maremma", ">= 4.9.4", "<= 5"
gem "addressable", "2.8.1"
gem "faraday", "~> 2.9"
gem "bolognese", "~> 2.3.2"
gem "json-ld-preloaded", "~> 3.1", ">= 3.1.3"
gem "dalli", "~> 3.2", ">= 3.2.8"
gem "lograge", "~> 0.11.2"
gem "logstash-event", "~> 1.2", ">= 1.2.02"
gem "logstash-logger", "~> 0.26.1"
gem "sentry-raven", "~> 3.1", ">= 3.1.2"
gem "gender_detector", "~> 0.1.2"
gem "rack-cors", "~> 1.0", require: "rack/cors"
gem "git", "~> 1.11"
gem "sprockets", "~> 3.7", ">= 3.7.2"

group :development, :test do
  gem "better_errors"
  gem "binding_of_caller"
  gem "listen", "~> 3.5"
  gem "rubocop", "~> 1.3", ">= 1.3.1"
  gem "rubocop-performance", "~> 1.5", ">= 1.5.1"
  gem "rubocop-rails", "~> 2.8", ">= 2.8.1"
  gem "spring"
  gem "spring-watcher-listen", "~> 2.0.0"
  gem "byebug"
  gem "rspec-rails", "~> 3.8", ">= 3.8.2"
  gem "capybara"
  gem "webmock", "~> 3.8", ">= 3.8.2"
  gem "vcr", "~> 5.1"
  gem "simplecov", "~> 0.17.1"
end
